fileprep: Remove unused scale parameter in determineScale (#187)
This fixes the following error:
```
error: unused parameter 'scale' [-Werror,-Wunused-parameter]
    351 |     auto calcScale = [](double scale, double low, double
    high)
```